# No runtime S3 registration needed; S3 methods are generated by roxygen2

# Silence R CMD check notes for non-standard evaluation in ggplot2 aesthetics
utils::globalVariables(c("term", "value", "p"))
